### ISSUE TITLE
govwayconsole - errore di lettura delle informazioni a runtime con piu' network abilitate

### ISSUE THREAD

**Issue by ilkosta** [link-it/govway-docker#8]
buongiorno,

provando ad abilitare piu' network nello stesso container, quando dalla console andiamo sulla voce `Runtime` del menu troviamo che vengono mostrati tutti i valori con `Informazione non disponibile`. 
Il problema si e' verificato solo dopo aver abilitato piu' interfacce di rete per lo stesso container.

Andando a consultare il file `govway_proxy.log` troviamo che stranamente le righe di log vanno a capo dopo il primo IP associato al container ed il log dell'errore e' il seguente:

```
ERROR <20-07-2022 12:42:22.874>: [Proxy] error occurs: (172.29.0.3
172.30.0.2) Servizio non disponibile 
 
java.lang.Exception: (172.29.0.3
172.30.0.2) Servizio non disponibile
        at org.openspcoop2.pdd.services.connector.Proxy.doGet(Proxy.java:342) ~[openspcoop2_pdd-3.3.6.jar:?]
        at org.openspcoop2.pdd.services.connector.OpenSPCoop2Servlet.dispatch(OpenSPCoop2Servlet.java:425) ~[openspcoop2_pdd-3.3.6.jar:?]
        at org.openspcoop2.pdd.services.connector.OpenSPCoop2Servlet.doGet(OpenSPCoop2Servlet.java:136) ~[openspcoop2_pdd-3.3.6.jar:?]
        at org.openspcoop2.pdd.services.connector.OpenSPCoop2Servlet.service(OpenSPCoop2Servlet.java:75) ~[openspcoop2_pdd-3.3.6.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[jboss-servlet-api_4.0_spec-2.0.0.Final.jar!/:2.0.0.Final]
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52) ~[?:?]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at org.openspcoop2.pdd.services.connector.ClientCertificateFilter.doFilter(ClientCertificateFilter.java:81) ~[openspcoop2_pdd-3.3.6.jar:?]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at org.openspcoop2.pdd.services.connector.FormUrlEncodedFilter.doFilter(FormUrlEncodedFilter.java:75) ~[openspcoop2_pdd-3.3.6.jar:?]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78) ~[?:?]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50) ~[undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61) ~[?:?]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68) ~[?:?]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105) ~[?:?]
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504) ~[?:?]
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504) ~[?:?]
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504) ~[?:?]
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504) ~[?:?]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99) [undertow-servlet-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830) [undertow-core-2.0.27.Final.jar!/:2.0.27.Final]
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) [jboss-threads-2.3.3.Final.jar!/:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982) [jboss-threads-2.3.3.Final.jar!/:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486) [jboss-threads-2.3.3.Final.jar!/:2.3.3.Final]
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377) [jboss-threads-2.3.3.Final.jar!/:2.3.3.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.openspcoop2.utils.UtilsException: Utilities.requestHTTPFile error Illegal character found in host: LF
        at org.openspcoop2.utils.transport.http.HttpUtilities.getHTTPResponse(HttpUtilities.java:675) ~[openspcoop2_utils-3.3.6.jar:?]
        at org.openspcoop2.pdd.services.connector.Proxy.invokeHttp(Proxy.java:450) ~[openspcoop2_pdd-3.3.6.jar:?]
        at org.openspcoop2.pdd.services.connector.Proxy.doGet(Proxy.java:308) ~[openspcoop2_pdd-3.3.6.jar:?]
        ... 57 more
Caused by: org.openspcoop2.utils.UtilsException: Illegal character found in host: LF
        at org.openspcoop2.utils.transport.http.HttpUtilities.httpInvoke(HttpUtilities.java:1407) ~[openspcoop2_utils-3.3.6.jar:?]
        at org.openspcoop2.utils.transport.http.HttpUtilities.getHTTPResponse(HttpUtilities.java:672) ~[openspcoop2_utils-3.3.6.jar:?]
        at org.openspcoop2.pdd.services.connector.Proxy.invokeHttp(Proxy.java:450) ~[openspcoop2_pdd-3.3.6.jar:?]
        at org.openspcoop2.pdd.services.connector.Proxy.doGet(Proxy.java:308) ~[openspcoop2_pdd-3.3.6.jar:?]
        ... 57 more
Caused by: java.net.MalformedURLException: Illegal character found in host: LF
        at java.net.URL.<init>(URL.java:679) ~[?:?]
        at java.net.URL.<init>(URL.java:541) ~[?:?]
        at java.net.URL.<init>(URL.java:488) ~[?:?]
        at org.openspcoop2.utils.transport.http.HttpUtilities.httpInvoke(HttpUtilities.java:1247) ~[openspcoop2_utils-3.3.6.jar:?]
        at org.openspcoop2.utils.transport.http.HttpUtilities.getHTTPResponse(HttpUtilities.java:672) ~[openspcoop2_utils-3.3.6.jar:?]
        at org.openspcoop2.pdd.services.connector.Proxy.invokeHttp(Proxy.java:450) ~[openspcoop2_pdd-3.3.6.jar:?]
        at org.openspcoop2.pdd.services.connector.Proxy.doGet(Proxy.java:308) ~[openspcoop2_pdd-3.3.6.jar:?]
        ... 57 more
Caused by: java.lang.IllegalArgumentException: Illegal character found in host: LF
        at java.net.URLStreamHandler.setURL(URLStreamHandler.java:504) ~[?:?]
        at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:312) ~[?:?]
        at java.net.URL.<init>(URL.java:674) ~[?:?]
        at java.net.URL.<init>(URL.java:541) ~[?:?]
        at java.net.URL.<init>(URL.java:488) ~[?:?]
        at org.openspcoop2.utils.transport.http.HttpUtilities.httpInvoke(HttpUtilities.java:1247) ~[openspcoop2_utils-3.3.6.jar:?]
        at org.openspcoop2.utils.transport.http.HttpUtilities.getHTTPResponse(HttpUtilities.java:672) ~[openspcoop2_utils-3.3.6.jar:?]
        at org.openspcoop2.pdd.services.connector.Proxy.invokeHttp(Proxy.java:450) ~[openspcoop2_pdd-3.3.6.jar:?]
        at org.openspcoop2.pdd.services.connector.Proxy.doGet(Proxy.java:308) ~[openspcoop2_pdd-3.3.6.jar:?]
        ... 57 more

```

come esempio la configurazione di rete del container risulta:

```json
{
"Networks": {
                "govway_336_db": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "app",
                        "593f71d366fb"
                    ],
                    "Gateway": "172.29.0.1",
                    "IPAddress": "172.29.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:1d:00:03",
                    "DriverOpts": null
                },
                "govway_336_proxynet": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "app",
                        "593f71d366fb"
                    ],
                    "Gateway": "172.30.0.1",
                    "IPAddress": "172.30.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:1e:00:02",
                    "DriverOpts": null
                }
            }
}
```

Occorre modificare qualche parametro di govway per abilitare il funzionamento su piu' schede di rete?
grazie

**Comment by ilkosta** [comment]
versione 3.3.7

**Comment by marklar79** [comment]
Ciao @ilkosta 

grazie per la segnalazione, in effetti si tratta di un problema che si verifica solamente in presenza di più reti sul container ed ha a che fare con la modalità con cui viene rilevato l'indirizzo ip del container dallo script di avvio.

Ho corretto il problema con il commit d4a0749c4bf94c095bf758595895416db60d6df1 .
La correzione sarà disponibile a partire dal rilascio della prossima versione di govway e quindi delle relative immagini docker.

Nel frattempo puoi fare un rebuild dell'immagine ed utilizzare quindi la tua immagine locale, oppure puoi modificare il container già attivo e committare la modifica come immagine locale. Ad esempio supponendo che il container si chiami govway_3.3.7_postgres:

```bash
docker cp commons/standalone_wrapper.sh govway_3.3.7_postgres:/tmp

docker exec --user root -t govway_3.3.7_postgres bash -c 'cp /tmp/standalone_wrapper.sh ${JBOSS_HOME}/bin/standalone_wrapper.sh; chown -R wildfly:0 ${JBOSS_HOME}/bin/standalone_wrapper.sh; chmod ug=rx ${JBOSS_HOME}/bin/standalone_wrapper.sh'

docker commit govway_3.3.7_postgres  linkitaly/govway:3.3.7v2_postgres
```

**Comment by ilkosta** [comment]
perfetto, grazie
